declare namespace NodeJS {
	interface ProcessEnv {
		// Protocol
		DEBUG_MODE: string;
		NEXT_PUBLIC_HTTP_PROTOCOLE: 'http' | 'https';
		HTTP: string;
		WS: string;
		ALLOWED_ORIGINS: string;
		// Next.js backend proxy (for cookies)
		NEXT_PUBLIC_BACKEND_DOMAIN: string;
		NEXT_PUBLIC_BACKEND_API: string;
		NEXT_PUBLIC_API_ROOT_URL: string;
		NEXT_PUBLIC_API_ROOT_PORT: string;
		NEXT_PUBLIC_API_URL: string;
		// Base URLs
		NEXT_PUBLIC_ROOT_API_URL: string;
		NEXT_PUBLIC_ROOT_WS_URL: string;
		NEXT_PUBLIC_WS_MAINTENANCE_ROOT: string;
		AUTH_TRUST_HOST: string;
		NEXTAUTH_SECRET: string;
		NEXTAUTH_URL: string;
		NEXT_PUBLIC_DOMAIN_URL_PREFIX: string;
		// Account
		NEXT_PUBLIC_ACCOUNT_ROOT: string;
		NEXT_PUBLIC_ACCOUNT_REFRESH_TOKEN: string;
		NEXT_PUBLIC_ACCOUNT_LOGIN: string;
		NEXT_PUBLIC_ACCOUNT_LOGOUT: string;
		NEXT_PUBLIC_ACCOUNT_CREATE_ACCOUNT: string;
		NEXT_PUBLIC_ACCOUNT_CHECK_EMAIL: string;
		NEXT_PUBLIC_ACCOUNT_PASSWORD_CHANGE: string;
		NEXT_PUBLIC_ACCOUNT_SEND_PASSWORD_RESET: string;
		NEXT_PUBLIC_ACCOUNT_PASSWORD_RESET: string;
		NEXT_PUBLIC_ACCOUNT_PROFIL: string;
		NEXT_PUBLIC_USERS_ROOT: string;
		// Reservations
		NEXT_PUBLIC_RESERVATION_ROOT: string;
		NEXT_PUBLIC_RESERVATION_LIST: string;
		NEXT_PUBLIC_RESERVATION_APARTMENTS: string;
		NEXT_PUBLIC_RESERVATION_DASHBOARD: string;
		NEXT_PUBLIC_RESERVATION_PLANNING: string;
		NEXT_PUBLIC_RESERVATION_BALANCE: string;
		NEXT_PUBLIC_RESERVATION_YEARS: string;
		NEXT_PUBLIC_RESERVATION_OCCUPIED_DATES: string;
		NEXT_PUBLIC_RESERVATION_COSTS: string;
		NEXT_PUBLIC_RESERVATION_COST_YEARS: string;
		// Notifications
		NEXT_PUBLIC_RESERVATION_NOTIFICATIONS: string;
		NEXT_PUBLIC_RESERVATION_NOTIFICATION_PREFERENCES: string;
		NEXT_PUBLIC_RESERVATION_NOTIFICATION_MARK_READ: string;
		NEXT_PUBLIC_RESERVATION_NOTIFICATION_UNREAD_COUNT: string;
		// Locaux
		NEXT_PUBLIC_LOCAL_LIST: string;
		NEXT_PUBLIC_LOYER_LIST: string;
		NEXT_PUBLIC_LOCAL_PLANNING: string;
		NEXT_PUBLIC_LOCAL_DASHBOARD: string;
		NEXT_PUBLIC_LOCAL_YEARS: string;
	}
}
