export type Language = 'fr' | 'en';

export type TranslationDictionary = {
	common: {
		yes: string;
		no: string;
		save: string;
		cancel: string;
		delete: string;
		edit: string;
		view: string;
		actions: string;
		add: string;
		back: string;
		update: string;
		confirm: string;
		search: string;
		loading: string;
		refresh: string;
		retry: string;
		submit: string;
		close: string;
		name: string;
		description: string;
		amount: string;
		date: string;
		category: string;
		status: string;
		notes: string;
		type: string;
		all: string;
		both: string;
		none: string;
		month: string;
		year: string;
		dashboard: string;
		skipToContent: string;
		identification: string;
		metadata: string;
		createdBy: string;
		creationDate: string;
		lastUpdate: string;
		deleteConfirmIrreversible: string;
		validationErrorsDetected: string;
		fixValidationErrors: string;
		errorDuringDeletion: string;
		deletedSuccess: string;
		address: string;
		paid: string;
		unpaid: string;
		rented: string;
		free: string;
		payment: string;
		total: string;
		rename: string;
		newName: string;
		selectValue: string;
		addImage: string;
		residence: string;
		noOptions: string;
		filterBy: string;
		errorOccurred: string;
		errorOccurredMessage: string;
		clickToModifyCrop: string;
		croppedPreview: string;
		togglePasswordVisibility: string;
		toggleDrawer: string;
		moreActions: string;
		maintenance: string;
		appName: string;
	};
	navigation: {
		dashboard: string;
		viewDashboard: string;
		reservations: string;
		reservationsList: string;
		newReservation: string;
		residences: string;
		residencesList: string;
		newResidence: string;
		locaux: string;
		locauxList: string;
		newLocal: string;
		rentPlanning: string;
		locauxDashboard: string;
		costs: string;
		costsList: string;
		newCost: string;
		analytics: string;
		monthlyPlanning: string;
		occupancyRate: string;
		balance: string;
		gainsRevenues: string;
		calendar: string;
		users: string;
		usersList: string;
		newUser: string;
		settings: string;
		myProfile: string;
		password: string;
		changePassword: string;
		notifications: string;
		notificationPreferences: string;
		logout: string;
		administration: string;
		welcomeMale: string;
		welcomeFemale: string;
		welcomeNeutral: string;
		markAllRead: string;
		noNotifications: string;
		loadMore: string;
		hiltonReports: string;
	};
	reservations: {
		apartment: string;
		guestName: string;
		checkIn: string;
		checkOut: string;
		amount: string;
		paymentSource: string;
		notes: string;
		reservation: string;
		reservationCount: string;
		// list
		reservationsList: string;
		newReservation: string;
		deleteBtnCount: (n: number) => string;
		deleteReservation: string;
		deleteReservationConfirm: string;
		reservationDeletedSuccess: string;
		reservationDeleteError: string;
		bulkDeleteReservations: (n: number) => string;
		bulkDeleteReservationsConfirm: string;
		bulkReservationsDeletedSuccess: (n: number) => string;
		bulkReservationsDeleteError: string;
		// columns
		columnAppartment: string;
		columnClient: string;
		columnCheckIn: string;
		columnCheckOut: string;
		columnNights: string;
		columnAmount: string;
		columnSource: string;
		allClients: string;
		// loading errors
		loadError: string;
		networkError: string;
		// view
		reservationDetails: string;
		reservationNumber: (id: number) => string;
		stayInfo: string;
		client: string;
		residence: string;
		arrival: string;
		departure: string;
		duration: string;
		nightCount: (n: number) => string;
		amountLabel: string;
		paymentSourceLabel: string;
		reservationNotFound: string;
		// dialog & form
		editReservation: string;
		reservationDetailsSection: string;
		stayDates: string;
		checkInRequired: string;
		checkOutRequired: string;
		apartmentRequired: string;
		guestNameRequired: string;
		totalAmountMAD: string;
		paymentSourceRequired: string;
		noApartmentFound: string;
		noSourceFound: string;
		notesOptional: string;
		addReservation: string;
		validationErrorsDetected: string;
		fixValidationErrors: string;
		reservationUpdatedSuccess: string;
		reservationAddedSuccess: string;
		reservationUpdateError: string;
		reservationAddError: string;
		// apartment management
		addBtn: string;
		editApartment: string;
		newApartmentName: string;
		apartmentEditedSuccess: string;
		apartmentEditError: string;
		deleteApartment: string;
		deleteApartmentConfirm: (name: string) => string;
		apartmentDeletedSuccess: string;
		apartmentDeleteError: string;
		noResidence: string;
		// calendar
		calendar: string;
		apartments: string;
		viewReservation: string;
		editReservationMenu: string;
		// planning
		monthlyPlanning: string;
		monthRevenue: string;
		nightStays: string;
		occupation: string;
		daysInMonth: string;
		noReservationForMonth: (month: string, year: number) => string;
		// balance
		balance: string;
		balanceYear: (year: number) => string;
		balanceScopeSubtitle: string;
		totalBalance: string;
		totalBalanceTooltip: string;
		amountReturned: string;
		amountReturnedTooltip: string;
		amountNotReturned: string;
		amountNotReturnedTooltip: string;
		apartmentCount: string;
		apartmentCountTooltip: string;
		reservationDetail: string;
		reservationDetailSubheader: (year: number) => string;
		toggleReturnedTooltip: string;
		returned: string;
		noDataForYear: (year: number) => string;
		revenueByApartmentMonth: string;
		revenueByApartmentMonthSub: (year: number) => string;
		matrixTooltip: string;
		// gains
		gainsRevenues: string;
		gainsRevenuesYear: (year: number) => string;
		gainsScopeSubtitle: string;
		totalGain: string;
		bestApartment: string;
		bestMonth: string;
		gainsByApartment: string;
		gainsByApartmentSub: string;
		gainsByApartmentTooltip: string;
		monthlyDetailByApartment: string;
		monthlyDetailByApartmentSub: (year: number) => string;
		monthlyDetailTooltip: string;
		// occupancy
		occupancyRate: string;
		occupancyRateYear: (year: number) => string;
		globalOccupation: string;
		globalOccupationTooltip: string;
		annualRevenue: string;
		annualRevenueTooltip: string;
		occupiedNights: string;
		occupiedNightsTooltip: (total: number) => string;
		freeNights: string;
		freeNightsTooltip: string;
		occupiedDaysByApartment: string;
		occupiedDaysByApartmentSub: (year: number) => string;
		occupiedDaysByApartmentTooltip: string;
		calendarView: string;
		calendarViewSub: string;
		calendarViewTooltip: string;
		vacant: string;
		occupiedPercent: (pct: number) => string;
		occupiedDaysCount: (occupied: number, total: number) => string;
		detailByApartment: string;
		detailByApartmentTooltip: string;
		daysLabel: string;
		reservationsLabel: string;
		revenueLabel: string;
		noDataAvailable: string;
		noDataForMonthYear: (month: string, year: number) => string;
		nightsTooltip: (n: number) => string;
		occupiedDaysChart: string;
	};
	buildings: {
		residence: string;
		residenceInfo: string;
		editResidence: string;
		newResidence: string;
		residenceUpdatedSuccess: string;
		residenceAddedSuccess: string;
		residenceUpdateError: string;
		residenceAddError: string;
		residenceDetail: string;
		residencesList: string;
		apartments: string;
		noApartments: string;
		noLocaux: string;
		deleteResidence: string;
		deleteResidenceConfirm: string;
		residenceDeletedSuccess: string;
		residenceDeleteError: string;
		bulkDeleteResidences: string;
		bulkDeleteResidencesConfirm: (n: number) => string;
		bulkResidencesDeletedSuccess: string;
		bulkResidencesDeleteError: string;
		loadError: string;
	};
	costs: {
		costDetails: string;
		costsList: string;
		editCost: string;
		newCost: string;
		costUpdatedSuccess: string;
		costAddedSuccess: string;
		costUpdateError: string;
		costAddError: string;
		costNotFound: string;
		costNumber: string;
		deleteCost: string;
		deleteCostConfirm: string;
		costDeletedSuccess: string;
		costDeleteError: string;
		bulkDeleteCosts: (n: number) => string;
		bulkDeleteCostsConfirm: string;
		bulkCostsDeletedSuccess: (n: number) => string;
		bulkCostsDeleteError: string;
		amountMAD: string;
		noCategoryFound: string;
	};
	locaux: {
		local: string;
		localInfo: string;
		localsList: string;
		editLocal: string;
		newLocal: string;
		localUpdatedSuccess: string;
		localAddedSuccess: string;
		localUpdateError: string;
		localAddError: string;
		localDetail: string;
		localNotFound: string;
		deleteLocal: string;
		deleteLocalConfirm: string;
		localDeletedSuccess: string;
		localDeleteError: string;
		bulkDeleteLocaux: string;
		bulkDeleteLocauxConfirm: (n: number) => string;
		bulkLocauxDeletedSuccess: string;
		bulkLocauxDeleteError: string;
		noResidenceFound: string;
		residence: string;
		noTypeFound: string;
		surface: string;
		surfaceUnit: string;
		financial: string;
		purchasePrice: string;
		purchasePriceMAD: string;
		monthlyRent: string;
		monthlyRentMAD: string;
		profitability: string;
		rental: string;
		inRental: string;
		tenantName: string;
		rentalStartDate: string;
		rents: string;
		noRentsForYear: (year: number) => string;
		editRent: string;
		addRent: string;
		monthRequired: string;
		yearRequired: string;
		amountMAD: string;
		paymentDate: string;
		rentMarkedUnpaid: string;
		rentMarkedPaid: string;
		rentUpdateError: string;
		rentUpdatedSuccess: string;
		rentAddedSuccess: string;
		rentDeletedSuccess: string;
		rentDeleteError: string;
		deleteRent: string;
		deleteRentConfirm: string;
		editResidence: string;
		deleteResidence: string;
		deleteResidenceConfirm: (name: string) => string;
		residenceEditedSuccess: string;
		residenceEditError: string;
		residenceDeletedSuccess: string;
		residenceDeleteImpossible: string;
		locauxDashboard: string;
		allResidences: string;
		profitHTYear: (year: number) => string;
		totalPaidMinusUnpaid: string;
		inRentalCount: string;
		inRentalTooltip: string;
		freeCount: string;
		freeTooltip: string;
		noLocauxRegistered: string;
		profitabilityByLocal: string;
		paidRents: string;
		unpaidRents: string;
		rentPerMonth: string;
		rentPlanning: string;
		rentPlanningYear: (year: number) => string;
		locauxCount: string;
		locauxCountTooltip: string;
		paidRentsCount: string;
		paidRentsTooltip: (count: number, year: number) => string;
		unpaidRentsCount: string;
		unpaidRentsTooltip: (count: number, year: number) => string;
		paymentRate: string;
		paymentRateTooltip: string;
		rentDetailByLocal: string;
		monthlyPaymentStatus: (year: number) => string;
		clickToChangeStatus: string;
		noRentRegistered: string;
		clickPaidUnpaidTooltip: (amount: string, action: string) => string;
		markUnpaid: string;
		markPaid: string;
	};
	analytics: {
		overviewYear: (year: number) => string;
		totalRevenue: string;
		totalRevenueTooltip: string;
		reservationCount: string;
		reservationCountTooltip: string;
		occupation: string;
		nightsOccupied: (n: number) => string;
		occupationTooltip: string;
		avgRevenuePerRes: string;
		avgRevenueTooltip: string;
		bestMonth: string;
		bestMonthTooltip: string;
		annualCosts: string;
		annualCostsTooltip: string;
		netProfit: string;
		netProfitTooltip: string;
		monthlyRevenue: string;
		monthlyRevenueSubheader: (year: number) => string;
		monthlyRevenueTooltip: string;
		monthlyTrend: string;
		monthlyTrendSubheader: string;
		monthlyTrendTooltip: string;
		sourceDistribution: string;
		sourceDistributionSubheader: string;
		sourceDistributionTooltip: string;
		revenueByApartment: string;
		revenueByApartmentSubheader: string;
		revenueByApartmentTooltip: string;
		occupancyByApartment: string;
		occupancyByApartmentSubheader: string;
		occupancyByApartmentTooltip: string;
		paymentSourceDetail: string;
		noDataAvailable: string;
		res: string;
		revenueChartLabel: string;
		occupiedDaysChartLabel: string;
	};
	users: {
		firstName: string;
		lastName: string;
		email: string;
		gender: string;
		admin: string;
		active: string;
		inactive: string;
		registrationDate: string;
		lastLogin: string;
		canView: string;
		canCreate: string;
		canEdit: string;
		canDelete: string;
		deleteUser: string;
		deleteUserConfirm: string;
		addUser: string;
		updateUser: string;
		editUser: string;
		userDetails: string;
		avatar: string;
		profilePhoto: string;
		personalInfo: string;
		accountSettings: string;
		permissions: string;
		activeAccount: string;
		adminAccount: string;
		userNotFound: string;
		userDeletedSuccess: string;
		userDeleteError: string;
		bulkDeleteUsers: (n: number) => string;
		bulkDeleteUsersConfirm: (n: number) => string;
		bulkUsersDeletedSuccess: (n: number) => string;
		bulkUsersDeleteError: string;
		generalInfo: string;
		usersList: string;
		newUser: string;
		deleteBtnCount: (n: number) => string;
		userId: string;
		administrator: string;
		userUpdatedSuccess: string;
		userAddedSuccess: string;
		userUpdateError: string;
		userAddError: string;
		addUserBtn: string;
		lastUpdated: string;
		canAccessHiltonReports: string;
	};
	hiltonReports: {
		title: string;
		subtitle: string;
		createReport: string;
		reportHistory: string;
		startDate: string;
		endDate: string;
		period: string;
		grossRevenue: string;
		manualCosts: string;
		manualAdjustments: string;
		netTotal: string;
		apartmentsRevenue: string;
		manualLines: string;
		lineType: string;
		cost: string;
		adjustment: string;
		note: string;
		addLine: string;
		noReports: string;
		noManualLines: string;
		preview: string;
		createSuccess: string;
		createError: string;
		emptyReportError: string;
		updateSuccess: string;
		updateError: string;
		deleteReport: string;
		deleteReportConfirm: string;
		deleteSuccess: string;
		deleteError: string;
		editReport: string;
		viewReport: string;
		latestOnlyDelete: string;
		reservationCount: string;
		reportNumber: (id: number) => string;
		building: string;
		createdAt: string;
		amount: string;
	};
	settings: {
		profile: string;
		editProfile: string;
		changePassword: string;
		oldPassword: string;
		newPassword: string;
		confirmNewPassword: string;
		defaultPasswordWarning: string;
		modify: string;
		updateSuccess: string;
		updateError: string;
		passwordChangeSuccess: string;
		passwordChangeError: string;
		notificationPreferences: string;
		checkInNotifications: string;
		checkOutNotifications: string;
		unpaidRentReminders: string;
		reminderDelay: string;
		notificationUpdateSuccess: string;
		notificationUpdateError: string;
		profileUpdateSuccess: string;
		profileUpdateError: string;
		genre: string;
		firstName: string;
		lastName: string;
		update: string;
		save: string;
		reminderOptions: { value: number; label: string }[];
	};
	auth: {
		login: string;
		emailAddress: string;
		password: string;
		forgotPassword: string;
		loginButton: string;
		serviceUnavailable: string;
		recovery: string;
		ofPassword: string;
		enterEmailDescription: string;
		resendCode: string;
		backToLogin: string;
		enterCode: string;
		codeSentTo: (email: string) => string;
		codeSent: string;
		codeSendFailed: string;
		confirmCode: string;
		newPassword: string;
		confirmPassword: string;
		changePasswordButton: string;
		passwordChanged: string;
		passwordChangedMessage: string;
	};
	validation: {
		required: string;
		shortRequired: string;
		minLength: (n: number) => string;
		maxLength: (n: number) => string;
		emailInvalid: string;
		passwordMinLength: (n: number) => string;
		apartmentRequired: string;
		dateRequired: (label: string) => string;
		invalidDateFormat: string;
		departureAfterArrival: string;
		passwordsDoNotMatch: string;
		localRequired: string;
		monthRequired: string;
		invalidMonth: string;
		yearRequired: string;
		invalidYear: string;
	};
	errors: {
		errorOccurred: string;
		errorApology: string;
		retryButton: string;
		refreshPage: string;
		pageNotFound: string;
		pageNotFoundText: string;
		accessDenied: string;
		accessDeniedText: string;
		maintenanceTitle: string;
		maintenanceText: string;
		maintenanceSuspended: string;
		maintenanceThanks: string;
		sessionExpired: string;
		networkError: string;
		unknownError: string;
		cannotConnectServer: string;
		unexpectedError: string;
		serverError: string;
		connectionCheckMessage: string;
		unauthorized: string;
		authenticationRequired: string;
	};
	notFound: {
		title: string;
		message: string;
		backBtn: string;
		homeBtn: string;
	};
	filters: {
		contains: string;
		equals: string;
		startsWith: string;
		endsWith: string;
		isEmpty: string;
		isNotEmpty: string;
		is: string;
		value: string;
		and: string;
		or: string;
		addFilter: string;
		removeAllFilters: string;
		activeFilters: (n: number) => string;
		allUsers: string;
		from: string;
		to: string;
		between: string;
	};
	dataGrid: {
		allMatchingSelected: (n: number) => string;
		clearSelection: string;
		pageItemsSelected: (n: number) => string;
		searchPlaceholder: string;
		selectAllMatching: (n: number) => string;
	};
	addEntityModal: {
		addEntity: (label: string) => string;
		entityName: (label: string) => string;
		entityNameRequired: (label: string) => string;
		entityAddError: (label: string) => string;
	};
	rawData: {
		genders: {
			male: string;
			female: string;
		};
		paymentSources: {
			cash: string;
			bankTransfer: string;
		};
		monthNames: string[];
		monthLabels: string[];
		monthLabelsShort: string[];
		dayAbbreviations: string[];
		costCategories: {
			maintenance: string;
			charges: string;
			insurance: string;
			taxes: string;
			other: string;
		};
		localTypes: {
			office: string;
			shop: string;
		};
		fieldLabels: {
			reservation: Record<string, string>;
			cost: Record<string, string>;
			local: Record<string, string>;
			loyer: Record<string, string>;
			building: Record<string, string>;
		};
		reminderOptions: {
			none: string;
			minutes15: string;
			minutes30: string;
			hour1: string;
			hours2: string;
			day1: string;
			days2: string;
		};
	};
	pageMetadata: {
		appTitle: string;
		appName: string;
		copyright: string;
		homeTitle: string;
		homeDescription: string;
		loginTitle: string;
		loginDescription: string;
		resetPasswordTitle: string;
		enterCodeTitle: string;
		enterCodeDescription: string;
		setPasswordTitle: string;
		setPasswordDescription: string;
		setPasswordCompleteTitle: string;
		setPasswordCompleteDescription: string;
		dashboardTitle: string;
		dashboardDescription: string;
		balanceTitle: string;
		balanceDescription: string;
		buildingsTitle: string;
		buildingsDescription: string;
		buildingsNewTitle: string;
		buildingsNewDescription: string;
		buildingsDetailTitle: string;
		buildingsDetailDescription: string;
		buildingsEditTitle: string;
		buildingsEditDescription: string;
		calendarTitle: string;
		calendarDescription: string;
		costsTitle: string;
		costsDescription: string;
		costsNewTitle: string;
		costsNewDescription: string;
		costsDetailTitle: string;
		costsDetailDescription: string;
		costsEditTitle: string;
		costsEditDescription: string;
		gainsTitle: string;
		gainsDescription: string;
		locauxTitle: string;
		locauxDescription: string;
		locauxNewTitle: string;
		locauxNewDescription: string;
		locauxDashboardTitle: string;
		locauxDashboardDescription: string;
		locauxPlanningTitle: string;
		locauxPlanningDescription: string;
		locauxDetailTitle: string;
		locauxDetailDescription: string;
		locauxEditTitle: string;
		locauxEditDescription: string;
		occupancyTitle: string;
		occupancyDescription: string;
		planningTitle: string;
		planningDescription: string;
		reservationsTitle: string;
		reservationsDescription: string;
		reservationsNewTitle: string;
		reservationsNewDescription: string;
		reservationsDetailTitle: string;
		reservationsDetailDescription: string;
		reservationsEditTitle: string;
		reservationsEditDescription: string;
		editProfileTitle: string;
		editProfileDescription: string;
		notificationsTitle: string;
		notificationsDescription: string;
		changePasswordTitle: string;
		changePasswordDescription: string;
		usersTitle: string;
		usersDescription: string;
		usersNewTitle: string;
		usersNewDescription: string;
		usersDetailTitle: string;
		usersDetailDescription: string;
		usersEditTitle: string;
		usersEditDescription: string;
		hiltonReportsTitle: string;
		hiltonReportsDescription: string;
	};
};
