import { isAiTextField } from './aiTextFields';
describe('AI text eligibility', () => {
	it.each(['description', 'notes', 'cost_period_label'])('enables reviewed writing field %s', (name) =>
		expect(isAiTextField(name, 'text')).toBe(true),
	);
	it.each([
		'barcode',
		'barCode',
		'code_barre',
		'reference',
		'numero_contrat',
		'code',
		'ICE',
		'rib',
		'incoterm_proforma',
		'raison_sociale',
		'nom',
		'prenom',
		'client_nom',
		'first_name',
		'last_name',
		'employee_first_name',
		'guest_name',
		'locataire_nom',
		'supplier_name',
		'fournisseur',
		'responsible',
		'responsable_projet',
		'architecte',
		'st_rep',
		'st_name',
		'name',
		'adresse',
		'client_adresse',
		'address',
		'st_addr',
		'ville_signature',
		'origine_marchandise',
		'banque',
		'banque_paiement',
		'st_banque',
		'transport',
		'superficie',
		'surface',
		'duree_estimee',
		'frais_redemarrage',
		'st_capital',
		'st_retenue_garantie',
		'st_avance',
		'st_plafond_penalite',
		'garantie_nb',
		'chantier_etage',
		'taxe_professionnelle',
		'prix_vente',
		'montant',
		'stock',
		'email',
		'client_cin',
		'client_cp',
		'search',
		'date_facture',
		'unknown_field',
		'new_bank',
		'edit_type',
	])('excludes identifiers, names, measurements and unreviewed fields: %s', (name) =>
		expect(isAiTextField(name, 'text')).toBe(false),
	);
	it.each(['number', 'date', 'email', 'password', 'checkbox', 'tel', 'url'])('excludes input type %s', (type) =>
		expect(isAiTextField('description', type)).toBe(false),
	);
});
